name: saltstack-grafana-formula
source: https://github.com/bechtoldt/saltstack-grafana-formula
summary: SaltStack formula to manage Grafana, a web-based visualizer of time series data
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
